// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-proxy/conf"
	"github.com/asynccnu/ccnubox-be/be-proxy/grpc"
	"github.com/asynccnu/ccnubox-be/be-proxy/ioc"
	"github.com/asynccnu/ccnubox-be/be-proxy/service"
	"github.com/asynccnu/ccnubox-be/common/pkg/grpcx"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	infraConf := conf.InitInfraConfig()
	logger := ioc.InitLogger(infraConf)
	transConf := conf.InitTransConfig()
	proxyService := service.NewProxyService(logger, transConf)
	proxyServiceServer := grpc.NewProxyServiceServer(proxyService)
	client := ioc.InitEtcdClient(infraConf)
	server := ioc.InitGRPCxKratosServer(proxyServiceServer, client, logger, transConf)
	return server
}
