// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-proxy/conf"
	"github.com/asynccnu/ccnubox-be/be-proxy/grpc"
	"github.com/asynccnu/ccnubox-be/be-proxy/ioc"
	"github.com/asynccnu/ccnubox-be/be-proxy/service"
)

// Injectors from wire.go:

func InitApp() *App {
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	proxyService := service.NewProxyService(logger, serverConf)
	proxyServiceServer := grpc.NewProxyServiceServer(proxyService)
	infraConf := conf.InitInfraConfig()
	client := ioc.InitEtcdClient(infraConf)
	server := ioc.InitGRPCxKratosServer(proxyServiceServer, client, logger, infraConf)
	v := ioc.InitOTel(serverConf)
	app := NewApp(server, v)
	return app
}
