// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-proxy/grpc"
	"github.com/asynccnu/ccnubox-be/be-proxy/ioc"
	"github.com/asynccnu/ccnubox-be/be-proxy/pkg/grpcx"
	"github.com/asynccnu/ccnubox-be/be-proxy/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	proxyService := service.NewProxyService()
	proxyServiceServer := grpc.NewProxyServiceServer(proxyService)
	client := ioc.InitEtcdClient()
	logger := ioc.InitLogger()
	server := ioc.InitGRPCxKratosServer(proxyServiceServer, client, logger)
	return server
}
