// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-banner/conf"
	"github.com/asynccnu/ccnubox-be/be-banner/grpc"
	"github.com/asynccnu/ccnubox-be/be-banner/ioc"
	"github.com/asynccnu/ccnubox-be/be-banner/repository/cache"
	"github.com/asynccnu/ccnubox-be/be-banner/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-banner/service"
	"github.com/asynccnu/ccnubox-be/common/pkg/grpcx"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	infraConf := conf.InitInfraConfig()
	logger := ioc.InitLogger(infraConf)
	db := ioc.InitDB(logger, infraConf)
	bannerDAO := dao.NewMysqlBannerDAO(db)
	cmdable := ioc.InitRedis(infraConf)
	bannerCache := cache.NewRedisBannerCache(cmdable)
	bannerService := service.NewBannerService(bannerDAO, bannerCache, logger)
	bannerServiceServer := grpc.NewBannerServiceServer(bannerService)
	transConf := conf.InitTransConfig()
	client := ioc.InitEtcdClient(transConf)
	server := ioc.InitGRPCxKratosServer(bannerServiceServer, client, logger, transConf)
	return server
}
