grpc:
  server:
    name: "counter"
    weight: 100
    addr: ":19085"
    etcdTTL: 60

etcd:
  endpoints:
    - "localhost:2379"
  username: root
  password: "12345678"

redis:
  addr: "localhost:6379"
  password: "12345678"

countLevel:
  low: 0 #轮询低位起始点
  middle: 3 #轮询中位起始点
  high: 6 #轮询高位起始点
  step: 3 #轮询降级与升级步数,即一次更改一级

log:
  path: "/logs/app.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）
