// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-counter/conf"
	"github.com/asynccnu/ccnubox-be/be-counter/grpc"
	"github.com/asynccnu/ccnubox-be/be-counter/ioc"
	"github.com/asynccnu/ccnubox-be/be-counter/repository/cache"
	"github.com/asynccnu/ccnubox-be/be-counter/service"
)

// Injectors from wire.go:

func InitApp() *App {
	infraConf := conf.InitInfraConfig()
	cmdable := ioc.InitRedis(infraConf)
	counterCache := cache.NewRedisCounterCache(cmdable)
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	counterService := service.NewCachedCounterService(counterCache, logger, serverConf)
	counterServiceServer := grpc.NewCounterServiceServer(counterService)
	client := ioc.InitEtcdClient(infraConf)
	server := ioc.InitGRPCxKratosServer(counterServiceServer, client, logger, infraConf)
	v := ioc.InitOTel(serverConf)
	app := NewApp(server, v)
	return app
}
