// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/biz/usecase"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/client"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/conf"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/crawler"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/events/delay"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/grpc"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/ioc"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/repository"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/repository/cache"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-classlist_v2/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	serverConf := conf.InitServerConf()
	infraConf := conf.InitInfraConfig()
	db := ioc.InitDB(infraConf)
	logger := ioc.InitLogger(serverConf)
	baseDAO, cleanup, err := dao.NewBaseDAO(db, logger)
	if err != nil {
		return nil, nil, err
	}
	classInfoDAO := dao.NewClassInfoDAO(baseDAO, logger)
	cmdable := ioc.InitRedis(infraConf)
	baseCache := cache.NewBaseCache(cmdable)
	classInfoCache := cache.NewClassInfoCache(baseCache, serverConf, logger)
	studentCourseDAO := dao.NewStudentCourseDAO(baseDAO, logger)
	studentCourseCache := cache.NewStudentCourseCache(baseCache, serverConf)
	classRepo := repo.NewClassRepo(classInfoDAO, classInfoCache, studentCourseDAO, studentCourseCache, logger)
	refreshLogDAO := dao.NewRefreshLogDAO(baseDAO)
	refreshLogRepo := repo.NewRefreshLogRepo(refreshLogDAO, logger)
	jxbDAO := dao.NewJxbDAO(baseDAO, logger)
	jxbRepo := repo.NewJxbRepo(jxbDAO)
	clientv3Client := ioc.InitEtcdClient(infraConf)
	userServiceClient := ioc.InitUserSvcClient(clientv3Client, infraConf)
	ccnuService := client.NewCCNUService(userServiceClient)
	proxyClient := ioc.InitProxyClient(clientv3Client, infraConf)
	proxyGetter := crawler.NewProxyGetter(proxyClient, logger)
	client2 := ioc.InitHttpProxyClient(proxyClient)
	crawler3 := crawler.NewClassCrawler3(proxyGetter, client2, logger)
	saramaClient := ioc.InitKafka(infraConf)
	delayKafkaConfig := delay.NewDelayKafkaConfig()
	delayQueue, cleanup2, err := delay.NewDelayKafka(saramaClient, delayKafkaConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	classUsecase := usecase.NewClassUsecase(serverConf, classRepo, refreshLogRepo, jxbRepo, ccnuService, crawler3, delayQueue, logger)
	classListService := service.NewClasserService(classUsecase, serverConf, logger)
	classlistServiceServer := grpc.NewCalendarServiceServer(classListService)
	server := ioc.InitGRPCxKratosServer(classlistServiceServer, clientv3Client, logger, infraConf)
	v := ioc.InitOTel(serverConf)
	app := NewApp(server, v)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
