// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/bff/conf"
	"github.com/asynccnu/ccnubox-be/bff/cron"
	"github.com/asynccnu/ccnubox-be/bff/ioc"
	"github.com/asynccnu/ccnubox-be/bff/web/middleware"
)

// Injectors from wire.go:

func InitApp() *App {
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	loggerMiddleware := middleware.NewLoggerMiddleware(logger)
	infraConf := conf.InitInfraConfig()
	client := ioc.InitRedis(infraConf)
	metrics := ioc.InitMetrics(serverConf)
	cmdable := ioc.RedisCmdable(client, metrics)
	_ = ioc.InitDAUCollector(metrics, cmdable, logger)
	handler := ioc.InitJwtHandler(cmdable, serverConf)
	clientv3Client := ioc.InitEtcdClient(infraConf)
	userServiceClient := ioc.InitUserClient(clientv3Client, infraConf)
	loginMiddleware := middleware.NewLoginMiddleWare(handler, userServiceClient)
	corsMiddleware := middleware.NewCorsMiddleware()
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware(serverConf)
	prometheusMiddleware := middleware.NewPrometheusMiddleware(metrics, cmdable)
	otelMiddleware := middleware.NewOtelMiddlerware()
	freeClassroomSvcClient := ioc.InitClassRoomClient(clientv3Client, infraConf)
	classRoomHandler := ioc.InitClassRoomHandler(freeClassroomSvcClient)
	tubePolicies := ioc.InitTubePolicies(serverConf)
	v := ioc.InitMac(serverConf)
	tubeHandler := ioc.InitTubeHandler(serverConf, tubePolicies, v)
	gradeServiceClient := ioc.InitGradeClient(clientv3Client, infraConf)
	classerClient := ioc.InitClassListClient(clientv3Client, infraConf)
	feedServiceClient := ioc.InitFeedClient(clientv3Client, infraConf)
	userHandler := ioc.InitUserHandler(logger, handler, userServiceClient, gradeServiceClient, classerClient, feedServiceClient)
	feedHandler := ioc.InitFeedHandler(serverConf, feedServiceClient)
	elecpriceServiceClient := ioc.InitElecpriceClient(clientv3Client, infraConf)
	elecPriceHandler := ioc.InitElecpriceHandler(serverConf, elecpriceServiceClient)
	counterServiceClient := ioc.InitCounterClient(clientv3Client, infraConf)
	gradeHandler := ioc.InitGradeHandler(serverConf, logger, gradeServiceClient, counterServiceClient)
	classHandler := ioc.InitClassHandler(serverConf, classerClient, logger)
	contentServiceClient := ioc.InitContentClient(clientv3Client, infraConf)
	contentHandler := ioc.InitContentHandler(serverConf, contentServiceClient, counterServiceClient, userServiceClient)
	metricsHandler := ioc.InitMetricsHandler(logger, cmdable, metrics)
	libraryServiceClient := ioc.InitLibrary(clientv3Client, infraConf)
	libraryHandler := ioc.InitLibraryHandler(serverConf, libraryServiceClient)
	swagHandler := ioc.InitSwagHandler()
	v2 := ioc.InitHealthClient(clientv3Client, infraConf)
	healthHandler := ioc.InitHealthHandler(v2)
	engine := ioc.InitGinServer(loggerMiddleware, loginMiddleware, corsMiddleware, basicAuthMiddleware, prometheusMiddleware, otelMiddleware, classRoomHandler, tubeHandler, userHandler, feedHandler, elecPriceHandler, gradeHandler, classHandler, contentHandler, metricsHandler, libraryHandler, swagHandler, healthHandler)
	v3 := ioc.InitOTel(serverConf, infraConf)
	refreshHandler := cron.NewTieredHandler(classerClient, gradeServiceClient, feedServiceClient, contentServiceClient, counterServiceClient, logger)
	redsync := ioc.InitRedisLock(client)
	tieredScheduler := ioc.InitScheduler(serverConf, refreshHandler, counterServiceClient, logger, redsync)
	app := NewApp(engine, serverConf, v3, tieredScheduler)
	return app
}
