// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/bff/conf"
	"github.com/asynccnu/ccnubox-be/bff/ioc"
	"github.com/asynccnu/ccnubox-be/bff/web/middleware"
)

// Injectors from wire.go:

func InitApp() *App {
	infraConf := conf.InitInfraConfig()
	logger := ioc.InitLogger(infraConf)
	loggerMiddleware := middleware.NewLoggerMiddleware(logger)
	cmdable := ioc.InitRedis(infraConf)
	transConf := conf.InitTransConfig()
	handler := ioc.InitJwtHandler(cmdable, transConf)
	client := ioc.InitEtcdClient(infraConf)
	userServiceClient := ioc.InitUserClient(client, transConf)
	loginMiddleware := middleware.NewLoginMiddleWare(handler, userServiceClient)
	corsMiddleware := middleware.NewCorsMiddleware()
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware()
	prometheusCounter := ioc.InitPrometheus(transConf)
	prometheusMiddleware := middleware.NewPrometheusMiddleware(prometheusCounter, cmdable)
	otelMiddleware := middleware.NewOtelMiddlerware()
	freeClassroomSvcClient := ioc.InitFreeClassroomClient(client, transConf)
	classRoomHandler := ioc.InitClassRoomHandler(freeClassroomSvcClient)
	tubePolicies := ioc.InitTubePolicies(transConf)
	credentials := ioc.InitMac(transConf)
	tubeHandler := ioc.InitTubeHandler(transConf, tubePolicies, credentials)
	userHandler := ioc.InitUserHandler(transConf, handler, userServiceClient)
	staticServiceClient := ioc.InitStaticClient(client, transConf)
	staticHandler := ioc.InitStaticHandler(transConf, staticServiceClient)
	bannerServiceClient := ioc.InitBannerClient(client, transConf)
	bannerHandler := ioc.InitBannerHandler(transConf, bannerServiceClient, userServiceClient)
	departmentServiceClient := ioc.InitDepartmentClient(client, transConf)
	departmentHandler := ioc.InitDepartmentHandler(transConf, departmentServiceClient)
	websiteServiceClient := ioc.InitWebsiteClient(client, transConf)
	websiteHandler := ioc.InitWebsiteHandler(transConf, websiteServiceClient)
	calendarServiceClient := ioc.InitCalendarClient(client, transConf)
	calendarHandler := ioc.InitCalendarHandler(transConf, calendarServiceClient)
	feedServiceClient := ioc.InitFeedClient(client, transConf)
	feedHandler := ioc.InitFeedHandler(transConf, feedServiceClient)
	elecpriceServiceClient := ioc.InitElecpriceClient(client, transConf)
	elecPriceHandler := ioc.InitElecpriceHandler(transConf, elecpriceServiceClient)
	gradeServiceClient := ioc.InitGradeClient(client, transConf)
	counterServiceClient := ioc.InitCounterClient(client, transConf)
	gradeHandler := ioc.InitGradeHandler(transConf, logger, gradeServiceClient, counterServiceClient)
	classerClient := ioc.InitClassList(client, transConf)
	classServiceClient := ioc.InitClassService(client, transConf)
	classHandler := ioc.InitClassHandler(transConf, classerClient, classServiceClient)
	feedbackHelpClient := ioc.InitFeedbackHelpClient(client, transConf)
	feedbackHelpHandler := ioc.InitFeedbackHelpHandler(transConf, feedbackHelpClient)
	infoSumServiceClient := ioc.InitInfoSumClient(client, transConf)
	infoSumHandler := ioc.InitInfoSumHandler(transConf, infoSumServiceClient)
	cardClient := ioc.InitCardClient(client, transConf)
	cardHandler := ioc.InitCardHandler(transConf, cardClient)
	metricsHandler := ioc.InitMetricsHandel(logger, cmdable, prometheusCounter)
	libraryClient := ioc.InitLibrary(client, transConf)
	libraryHandler := ioc.InitLibraryHandler(transConf, libraryClient)
	swagHandler := ioc.InitSwagHandler()
	engine := ioc.InitGinServer(loggerMiddleware, loginMiddleware, corsMiddleware, basicAuthMiddleware, prometheusMiddleware, otelMiddleware, classRoomHandler, tubeHandler, userHandler, staticHandler, bannerHandler, departmentHandler, websiteHandler, calendarHandler, feedHandler, elecPriceHandler, gradeHandler, classHandler, feedbackHelpHandler, infoSumHandler, cardHandler, metricsHandler, libraryHandler, swagHandler)
	app := NewApp(engine)
	return app
}
