// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/bff/conf"
	"github.com/asynccnu/ccnubox-be/bff/ioc"
	"github.com/asynccnu/ccnubox-be/bff/web/middleware"
)

// Injectors from wire.go:

func InitApp() *App {
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	loggerMiddleware := middleware.NewLoggerMiddleware(logger)
	infraConf := conf.InitInfraConfig()
	cmdable := ioc.InitRedis(infraConf)
	handler := ioc.InitJwtHandler(cmdable, serverConf)
	client := ioc.InitEtcdClient(infraConf)
	userServiceClient := ioc.InitUserClient(client, infraConf)
	loginMiddleware := middleware.NewLoginMiddleWare(handler, userServiceClient)
	corsMiddleware := middleware.NewCorsMiddleware()
	basicAuthMiddleware := middleware.NewBasicAuthMiddleware(serverConf)
	prometheusCounter := ioc.InitPrometheus(serverConf)
	prometheusMiddleware := middleware.NewPrometheusMiddleware(prometheusCounter, cmdable)
	otelMiddleware := middleware.NewOtelMiddlerware()
	freeClassroomSvcClient := ioc.InitClassRoomClient(client, infraConf)
	classRoomHandler := ioc.InitClassRoomHandler(freeClassroomSvcClient)
	tubePolicies := ioc.InitTubePolicies(serverConf)
	credentials := ioc.InitMac(serverConf)
	tubeHandler := ioc.InitTubeHandler(serverConf, tubePolicies, credentials)
	gradeServiceClient := ioc.InitGradeClient(client, infraConf)
	classerClient := ioc.InitClassListClient(client, infraConf)
	feedServiceClient := ioc.InitFeedClient(client, infraConf)
	userHandler := ioc.InitUserHandler(logger, handler, userServiceClient, gradeServiceClient, classerClient, feedServiceClient)
	feedHandler := ioc.InitFeedHandler(serverConf, feedServiceClient)
	elecpriceServiceClient := ioc.InitElecpriceClient(client, infraConf)
	elecPriceHandler := ioc.InitElecpriceHandler(serverConf, elecpriceServiceClient)
	counterServiceClient := ioc.InitCounterClient(client, infraConf)
	gradeHandler := ioc.InitGradeHandler(serverConf, logger, gradeServiceClient, counterServiceClient)
	classServiceClient := ioc.InitClassClient(client, infraConf)
	classHandler := ioc.InitClassHandler(serverConf, classerClient, classServiceClient)
	contentServiceClient := ioc.InitContentClient(client, infraConf)
	contentHandler := ioc.InitContentHandler(contentServiceClient, userServiceClient, gradeServiceClient, serverConf)
	metricsHandler := ioc.InitMetricsHandel(logger, cmdable, prometheusCounter)
	libraryClient := ioc.InitLibrary(client, infraConf)
	libraryHandler := ioc.InitLibraryHandler(serverConf, libraryClient)
	swagHandler := ioc.InitSwagHandler()
	engine := ioc.InitGinServer(loggerMiddleware, loginMiddleware, corsMiddleware, basicAuthMiddleware, prometheusMiddleware, otelMiddleware, classRoomHandler, tubeHandler, userHandler, feedHandler, elecPriceHandler, gradeHandler, classHandler, contentHandler, metricsHandler, libraryHandler, swagHandler)
	v := ioc.InitOTel(serverConf)
	app := NewApp(engine, serverConf, v)
	return app
}
