serviceName: "bff"

http:
  addr: ":8080"

administrators:
  - "1234567890"

jwt:
  jwtKey: ""
  refreshKey: ""
  encKey: "ccnubox"

oss:
  accessKey: ""
  secretKey: ""
  bucketName: ""
  domainName: "" # CDN 域名
  baseName: ""
  fileName: ""


# 日志配置
log:
  path: "/logs/app.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）

# Prometheus 配置
prometheus:
  namespace: "ccnubox" # Prometheus 命名空间，通常为项目名称

  routerCounter:
    name: "http_requests_total"  # 路由请求总数指标名称
    help: "Total number of HTTP requests" # 指标说明

  activeConnections:
    name: "active_connections"  # 活跃连接指标名称
    help: "Number of active connections per route" # 指标说明

  durationTime:
    name: "http_request_duration_seconds"  # 请求时长直方图名称
    help: "Histogram of response times for HTTP requests" # 指标说明

  dailyActiveUsers:
    name: "daily_active_users"
    help: "Number of active users in last 24 hours calculated by Redis HyperLogLog"

basicAuth:
  username: ""
  password: ""

tiered:
  high: 15  #单位是分钟
  middle: 30 #单位是分钟
  low: 60 #单位是分钟
