env: "prod"

server:
  name: "ccnu"
  grpc:
    addr: "0.0.0.0:19082"
    timeout: 10s

registry:
  etcd:
    addr: "localhost:2379"
    username: "root"
    password: ""

data:
  proxy:
    endpoint: "discovery:///proxy"

log:
  path: "/logs/app.log"
  maxSize: 100
  maxBackups: 7
  maxAge: 30
  compress: 1

otel:
  serviceName: "be-ccnu"
  serviceVersion: "1.0.0"
  endpoint: "localhost:4318"

crypto:
  secret: ""  # 加密密钥