etcd:
  endpoints:
    - "localhost:12379"

grpc:
  server:
    name: "ccnu"
    weight: 100
    addr: ":8092"
    etcdTTL: 60


log:
  path: "./logs/app.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）
