// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-content/cron"
	"github.com/asynccnu/ccnubox-be/be-content/grpc"
	"github.com/asynccnu/ccnubox-be/be-content/ioc"
	"github.com/asynccnu/ccnubox-be/be-content/repository"
	"github.com/asynccnu/ccnubox-be/be-content/service"
)

// Injectors from wire.go:

func InitApp() App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	cmdable := ioc.InitRedis()
	contentRepo := repository.ProvideCalendarRepo(db, cmdable, logger)
	calendarService := service.NewCalendarService(contentRepo, logger)
	repositoryContentRepo := repository.ProvideBannerRepo(db, cmdable, logger)
	bannerService := service.NewBannerService(repositoryContentRepo, logger)
	contentRepo2 := repository.ProvideDepartmentRepo(db, cmdable, logger)
	departmentService := service.NewDepartmentService(contentRepo2, logger)
	contentRepo3 := repository.ProvideWebsiteRepo(db, cmdable, logger)
	websiteService := service.NewWebsiteService(contentRepo3, logger)
	contentRepo4 := repository.ProvideInfoSumRepo(db, cmdable, logger)
	infoSumService := service.NewInfoSumService(contentRepo4, logger)
	contentServiceServer := grpc.NewCalendarServiceServer(calendarService, bannerService, departmentService, websiteService, infoSumService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(contentServiceServer, client, logger)
	qiniuClient := ioc.InitQiniu()
	calendarController := cron.NewCalendarController(calendarService, qiniuClient, logger)
	v := cron.NewCron(calendarController)
	app := NewApp(server, v)
	return app
}
