// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-grade/conf"
	"github.com/asynccnu/ccnubox-be/be-grade/events"
	"github.com/asynccnu/ccnubox-be/be-grade/events/producer"
	"github.com/asynccnu/ccnubox-be/be-grade/grpc"
	"github.com/asynccnu/ccnubox-be/be-grade/ioc"
	"github.com/asynccnu/ccnubox-be/be-grade/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-grade/service"
)

// Injectors from wire.go:

func InitApp() App {
	infraConf := conf.InitInfraConfig()
	db := ioc.InitDB(infraConf)
	gradeDAO := dao.NewGradeDAO(db)
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	client := ioc.InitEtcdClient(infraConf)
	userServiceClient := ioc.InitUserClient(client, infraConf)
	classerClient := ioc.InitClassListClient(client, infraConf)
	proxyClient := ioc.InitProxyClient(client, infraConf)
	client2 := ioc.InitHttpProxyClient(proxyClient, logger)
	saramaClient := ioc.InitKafka(infraConf)
	producerProducer := producer.NewSaramaProducer(saramaClient)
	gradeService := service.NewGradeService(gradeDAO, logger, userServiceClient, classerClient, client2, producerProducer)
	rankDAO := dao.NewRankDAO(db)
	rankService := service.NewRankService(rankDAO, logger, userServiceClient)
	gradeServiceServer := grpc.NewGradeGrpcService(gradeService, rankService)
	server := ioc.InitGRPCxKratosServer(gradeServiceServer, client, logger, infraConf)
	gradeDetailEventConsumerHandler := events.NewGradeDetailEventConsumerHandler(saramaClient, logger, gradeService, serverConf)
	v := ioc.InitConsumers(gradeDetailEventConsumerHandler)
	v2 := ioc.InitOTel(infraConf)
	app := NewApp(server, v, v2)
	return app
}
