// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-elecprice/cron"
	"github.com/asynccnu/ccnubox-be/be-elecprice/grpc"
	"github.com/asynccnu/ccnubox-be/be-elecprice/ioc"
	"github.com/asynccnu/ccnubox-be/be-elecprice/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-elecprice/service"
)

// Injectors from wire.go:

func InitApp() App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	elecpriceDAO := dao.NewElecpriceDAO(db)
	client := ioc.InitEtcdClient()
	proxyClient := ioc.InitProxyClient(client)
	elecpriceService := service.NewElecpriceService(elecpriceDAO, logger, proxyClient)
	elecpriceServiceServer := grpc.NewElecpriceGrpcService(elecpriceService)
	server := ioc.InitGRPCxKratosServer(elecpriceServiceServer, client, logger)
	feedServiceClient := ioc.InitFeedClient(client)
	elecpriceController := cron.NewElecpriceController(feedServiceClient, elecpriceService, logger)
	v := cron.NewCron(elecpriceController)
	app := NewApp(server, v)
	return app
}
