apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-grade
  namespace: ccnube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: be-grade
  template:
    metadata:
      labels:
        app: be-grade
    spec:
      containers:
        - name: be-grade
          image: be-grade:v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 19089
          volumeMounts:
            - name: config-volume
              mountPath: /data/conf
      volumes:
        - name: config-volume
          configMap:
            name: ccnube-config
            items:
              - key: be-grade.yaml
                path: config.yaml