apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: ccnube
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.4.15
          command:
            - "/usr/local/bin/etcd"
            - "--name=etcd0"
            - "--data-dir=/etcd-data"
            - "--listen-peer-urls=http://0.0.0.0:2380"
            - "--listen-client-urls=http://0.0.0.0:2379"
            - "--advertise-client-urls=http://etcd:2379"
            - "--initial-cluster=etcd0=http://etcd:2380"
            - "--initial-cluster-state=new"
            - "--initial-cluster-token=etcd-cluster-1"
            - "--initial-advertise-peer-urls=http://etcd:2380"
          ports:
            - containerPort: 2379
            - containerPort: 2380
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: ccnube
spec:
  clusterIP: None  # Headless Service，允许 DNS 查询每个 Pod 的 IP
  selector:
    app: etcd  # 选择器要匹配 StatefulSet 中的 label
  ports:
    - port: 2379  # etcd 客户端访问端口
      name: client
    - port: 2380  # etcd 节点之间的通信端口
      name: peer


# kubectl exec -it etcd-0 -n ccnube -- etcdctl user add admin:muxistudio304
# kubectl exec -it etcd-0 -n ccnube -- etcdctl role add root
# kubectl exec -it etcd-0 -n ccnube -- etcdctl user grant-role admin root