apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ccnube
spec:
  clusterIP: None  # Headless Service
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: ccnube
spec:
  serviceName: redis  # 必须和上面的 service name 一致
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          command: ["/bin/sh"]
          args:
            - -c
            - |
              if [ "$(hostname)" = "redis-0" ]; then
                redis-server --appendonly yes --requirepass muxistudio304
              else
                redis-server --replicaof redis-0.redis.ccnube.svc.cluster.local 6379 --masterauth muxistudio304 --appendonly yes --requirepass muxistudio304
              fi
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
