// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-library/conf"
	"github.com/asynccnu/ccnubox-be/be-library/crawler"
	"github.com/asynccnu/ccnubox-be/be-library/grpc"
	"github.com/asynccnu/ccnubox-be/be-library/ioc"
	"github.com/asynccnu/ccnubox-be/be-library/service"
)

// Injectors from wire.go:

func InitApp() App {
	infraConf := conf.InitInfraConfig()
	client := ioc.InitEtcdClient(infraConf)
	userServiceClient := ioc.InitUserClient(client, infraConf)
	proxyClient := ioc.InitProxyClient(client, infraConf)
	client2 := ioc.InitHttpProxyClient(proxyClient)
	httpClient := crawler.InitCrawlerHttpClient(client2)
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	string2 := ioc.InitSecret(serverConf)
	crawlerCrawler := crawler.NewLibraryCrawlerMust(httpClient, logger, string2)
	seatService := service.NewSeatService(userServiceClient, crawlerCrawler, logger)
	discussionService := service.NewDiscussionService(userServiceClient, crawlerCrawler, logger)
	libraryServiceServer := grpc.NewLibraryGrpcService(seatService, discussionService)
	server := ioc.InitGRPCxKratosServer(libraryServiceServer, client, logger, infraConf)
	v := ioc.InitNoopShutdown()
	app := NewApp(server, v)
	return app
}
