env: "prod"

server:
  name: "counter"
  grpc:
    addr: "0.0.0.0:19085"
    timeout: 10s

data:
  mysql:
    dsn: "root:password@tcp(localhost:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    addr: "localhost:6379"
    password: ""
  etcd:
    endpoints:
      - "localhost:2379"
    username: "root"
    password: ""

registry:
  etcd:
    addr: "localhost:2379"
    username: "root"
    password: ""

countLevel:
  low: 0      # 轮询低位起始点
  middle: 3   # 轮询中位起始点
  high: 6     # 轮询高位起始点
  step: 3     # 轮询降级与升级步数

log:
  path: "/logs/app.log"
  maxSize: 100
  maxBackups: 7
  maxAge: 30
  compress: 1

otel:
  serviceName: "be-counter"
  serviceVersion: "1.0.0"
  endpoint: "localhost:4318"