// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-user/conf"
	"github.com/asynccnu/ccnubox-be/be-user/grpc"
	"github.com/asynccnu/ccnubox-be/be-user/ioc"
	"github.com/asynccnu/ccnubox-be/be-user/repository/cache"
	"github.com/asynccnu/ccnubox-be/be-user/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-user/service"
)

// Injectors from wire.go:

func InitApp() *App {
	infraConf := conf.InitInfraConfig()
	db := ioc.InitDB(infraConf)
	userDAO := dao.NewGORMUserDAO(db)
	cmdable := ioc.InitRedis(infraConf)
	userCache := cache.NewRedisUserCache(cmdable)
	crypto := ioc.NewCrypto()
	client := ioc.InitEtcdClient(infraConf)
	ccnuServiceClient := ioc.InitCCNUClient(client, infraConf)
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	proxyClient := ioc.InitProxyClient(client, infraConf)
	userService := service.NewUserService(userDAO, userCache, crypto, ccnuServiceClient, logger, proxyClient)
	userServiceServer := grpc.NewUserServiceServer(userService)
	server := ioc.InitGRPCxKratosServer(userServiceServer, client, logger, infraConf)
	v := ioc.InitOTel(serverConf)
	app := NewApp(server, v)
	return app
}
