env: "prod"

server:
  name: "proxy"
  grpc:
    addr: "0.0.0.0:19094"
    timeout: 10s

data:
  etcd:
    endpoints:
      - "localhost:2379"
    username: "root"
    password: ""

registry:
  etcd:
    addr: "localhost:2379"
    username: "root"
    password: ""

log:
  path: "/logs/app.log"
  maxSize: 100
  maxBackups: 7
  maxAge: 30
  compress: 1

otel:
  serviceName: "be-proxy"
  serviceVersion: "1.0.0"
  endpoint: "localhost:4318"

shenlongConf:
  api: "http://api.shenlongip.com/ip?key=xxx&protocol=1&mr=1&pattern=txt&count=1&sign=xxxx"
  interval: 100
  retry: 3
  username: "xxx"
  password: "xxx"