// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-ccnu/conf"
	"github.com/asynccnu/ccnubox-be/be-ccnu/grpc"
	"github.com/asynccnu/ccnubox-be/be-ccnu/ioc"
	"github.com/asynccnu/ccnubox-be/be-ccnu/service"
)

// Injectors from wire.go:

func InitApp() *App {
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	infraConf := conf.InitInfraConfig()
	client := ioc.InitEtcdClient(infraConf)
	proxyClient := ioc.InitProxyClient(client, infraConf)
	ccnuService := service.NewCCNUService(logger, proxyClient)
	ccnuServiceServer := grpc.NewCCNUServiceServer(ccnuService)
	server := ioc.InitGRPCxKratosServer(ccnuServiceServer, client, logger, infraConf)
	v := ioc.InitOTel(serverConf)
	app := NewApp(server, v)
	return app
}
