// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-ccnu/conf"
	"github.com/asynccnu/ccnubox-be/be-ccnu/grpc"
	"github.com/asynccnu/ccnubox-be/be-ccnu/ioc"
	"github.com/asynccnu/ccnubox-be/be-ccnu/service"
	"github.com/asynccnu/ccnubox-be/common/pkg/grpcx"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	infraConf := conf.InitInfraConfig()
	logger := ioc.InitLogger(infraConf)
	client := ioc.InitEtcdClient(infraConf)
	transConf := conf.InitTransConfig()
	proxyClient := ioc.InitProxyClient(client, transConf)
	ccnuService := service.NewCCNUService(logger, proxyClient)
	ccnuServiceServer := grpc.NewCCNUServiceServer(ccnuService)
	server := ioc.InitGRPCxKratosServer(ccnuServiceServer, client, logger, transConf)
	return server
}
