env: "prod"

server:
  name: "user"
  grpc:
    addr: "0.0.0.0:19091"
    timeout: 10s

data:
  mysql:
    dsn: "root:password@tcp(localhost:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    addr: "localhost:6379"
    password: ""
  etcd:
    endpoints:
      - "localhost:2379"
    username: "root"
    password: ""

registry:
  etcd:
    addr: "localhost:2379"
    username: "root"
    password: ""

grpc:
  client:
    ccnu:
      endpoint: "discovery:///ccnu"
      retryCnt: 3
    proxy:
      endpoint: "discovery:///proxy"

log:
  path: "/logs/app.log"
  maxSize: 100
  maxBackups: 7
  maxAge: 30
  compress: 1

otel:
  serviceName: "be-user"
  serviceVersion: "1.0.0"
  endpoint: "localhost:4318"