// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-class/internal/biz"
	"github.com/asynccnu/ccnubox-be/be-class/internal/client"
	"github.com/asynccnu/ccnubox-be/be-class/internal/conf"
	"github.com/asynccnu/ccnubox-be/be-class/internal/data"
	"github.com/asynccnu/ccnubox-be/be-class/internal/lock"
	"github.com/asynccnu/ccnubox-be/be-class/internal/registry"
	"github.com/asynccnu/ccnubox-be/be-class/internal/server"
	"github.com/asynccnu/ccnubox-be/be-class/internal/service"
	"github.com/asynccnu/ccnubox-be/be-class/internal/timedTask"
	"github.com/go-kratos/kratos/v2/log"
	"io"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(string2 string, confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger, writer io.Writer) (*APP, func(), error) {
	elasticClient, err := data.NewEsClient(confData)
	if err != nil {
		return nil, nil, err
	}
	classData, cleanup, err := data.NewClassData(elasticClient)
	if err != nil {
		return nil, nil, err
	}
	etcdRegistry := registry.NewRegistrarServer(confRegistry)
	env := client.NewEnv(string2)
	classListService, err := client.NewClassListService(etcdRegistry, confRegistry, env)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient := data.NewRedisClient(confData)
	builder := lock.NewRedisLockBuilder(redisClient)
	cache := data.NewCache(redisClient)
	classServiceUserCase := biz.NewClassServiceUserCase(classData, classListService, builder, cache)
	userSvc, err := client.NewUserSvc(etcdRegistry, confRegistry, env)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	db := data.NewDB(confData, writer)
	cultivateStrategyData := data.NewCultivateStrategyData(db, confData)
	proxyClient, err := client.InitProxyClient(etcdRegistry, confRegistry, logger, env)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cultivateStrategy := biz.NewCultivateStrategyBiz(userSvc, cache, cultivateStrategyData, proxyClient)
	classServiceService := service.NewClassServiceService(classServiceUserCase, cultivateStrategy)
	freeClassroomData := data.NewFreeClassroomData(elasticClient)
	freeClassroomBiz := biz.NewFreeClassroomBiz(classData, freeClassroomData, userSvc, builder, cache, proxyClient)
	freeClassroomSvc := service.NewFreeClassroomSvc(freeClassroomBiz)
	grpcServer := server.NewGRPCServer(confServer, classServiceService, freeClassroomSvc, logger)
	selectionUploader := service.NewSelectionUploader(freeClassroomBiz)
	httpServer := server.NewHTTPServer(confServer, selectionUploader)
	app := newApp(logger, grpcServer, httpServer, etcdRegistry, confServer, env)
	task := timedTask.NewTask(classServiceUserCase, freeClassroomBiz, classListService)
	mainAPP := NewApp(app, task)
	return mainAPP, func() {
		cleanup()
	}, nil
}
