// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-calendar/conf"
	"github.com/asynccnu/ccnubox-be/be-calendar/cron"
	"github.com/asynccnu/ccnubox-be/be-calendar/grpc"
	"github.com/asynccnu/ccnubox-be/be-calendar/ioc"
	"github.com/asynccnu/ccnubox-be/be-calendar/repository/cache"
	"github.com/asynccnu/ccnubox-be/be-calendar/repository/dao"
	"github.com/asynccnu/ccnubox-be/be-calendar/service"
)

// Injectors from wire.go:

func InitApp() App {
	infraConf := conf.InitInfraConfig()
	logger := ioc.InitLogger(infraConf)
	db := ioc.InitDB(logger, infraConf)
	calendarDAO := dao.NewMysqlCalendarDAO(db)
	cmdable := ioc.InitRedis(infraConf)
	calendarCache := cache.NewRedisCalendarCache(cmdable)
	calendarService := service.NewCachedCalendarService(calendarDAO, calendarCache, logger)
	calendarServiceServer := grpc.NewCalendarServiceServer(calendarService)
	transConf := conf.InitTransConfig()
	client := ioc.InitEtcdClient(transConf)
	server := ioc.InitGRPCxKratosServer(calendarServiceServer, client, logger, transConf)
	qiniuClient := ioc.InitQiniu(transConf)
	calendarController := cron.NewCalendarController(calendarService, qiniuClient, logger, transConf)
	feedServiceClient := ioc.InitFeedClient(client, transConf)
	holidayController := cron.NewHolidayController(feedServiceClient, logger, transConf)
	v := cron.NewCron(calendarController, holidayController)
	app := NewApp(server, v)
	return app
}
