mysql:
  dsn: "root:12345678@tcp(localhost:13306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"


redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:2379"
  username: root
  password: "12345678"

grpc:
  server:
    name: "elecprice"
    weight: 100
    addr: ":19087"
    etcdTTL: 60
  client:
    feed:
      endpoint: "discovery:///feed"

#电费成绩
elecpriceController:
  durationTime: 24 # 检查周期,每24小时检查一次
  
log:
  path: "./logs/app.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）

