name: Build and Deploy - be-feed

on:
  push:
    paths:
      - 'be-feed/**'

jobs:
  build-be-feed:
    if: github.repository == 'asynccnu/ccnubox-be'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com

      - name: Build and push image
        run: |
          chmod +x ./build-be-feed.sh
          ./build-be-feed.sh ${{ secrets.IMAGE_REPO }}

  deploy:
    if: github.repository == 'asynccnu/ccnubox-be'
    runs-on: ubuntu-latest
    needs: build-be-feed
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_ADDR }} >> ~/.ssh/known_hosts

      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDR }} << 'EOF'
            cd ~/ccnubox
            kubectl apply -f namespace.yaml || true
            kubectl apply -f config-map.yaml || true
            kubectl delete -f be-feed.yaml || true
            kubectl apply -f be-feed.yaml || true
          EOF
